name: Build & Deploy
on: [push, workflow_dispatch]
env:
  REACT_APP_SECRET_CODE: 1234567
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Create .env file
        uses: skiddph/actions-env@v1.0.2
        with:
          file: .env
        env:
          REACT_APP_SECRET_CODE: ${{ env.REACT_APP_SECRET_CODE }}
      - name: Build project
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build project
        uses: actions/download-artifact@v3
        with:
          name: build-files
