name: Build & Deploy
on: [push, workflow_dispatch]
env:
  REACT_APP_SECRET_CODE: 1234567
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Build project
        run: npx cross-env REACT_APP_SECRET_CODE=${{ env.REACT_APP_SECRET_CODE }} react-scripts build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build project
        uses: actions/download-artifact@v3
        with:
          name: build-files
